version: "3.1"
services:
  # backend-chocadeira:
  #   image: node:alpine
  #   container_name: backend-chocadeira
  #   volumes:
  #       - ./backend:/backend
  #   working_dir: /backend
  #   # command: npm install
  #   command: npm run start:dev
  #   ports:
  #       - "9000:9000"
  #   depends_on:
  #       - postgres
  #   environment:
  #       - CHOKIDAR_USEPOLLING=true
  # frontend-chocadeira:
  #     image: node:alpine
  #     stdin_open: true
  #     container_name: frontend-chocadeira
  #     volumes:
  #         - ./frontend:/frontend
  #     working_dir: /frontend
  #     # command: npm install
  #     command: npm start
  #     ports:
  #         - "3000:3000"
  #     environment:
  #         - CHOKIDAR_USEPOLLING=true
  #     depends_on:
  #         - backend-chocadeira
  postgres:
    image: postgres:11.1-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=chocadeira
    ports:
      - "8892:5432"
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com.br"
      PGADMIN_DEFAULT_PASSWORD: "admin!"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
